spring:
  application:
    name: API-notification

  datasource:
    url: jdbc:mysql://localhost:3308/db_notification
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
