spring:
  application:
    name: API-notification

  datasource:
    url: jdbc:mysql://db:3306/db_notification
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

