services:
  db:
    container_name: mysql-notification
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=db_notification'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secretroot'
      - 'MYSQL_USER=myuser'
    ports:
      - '3308:3306'

    volumes:
      - mysql_data:/var/lib/mysql

  api:
    image: notification
    container_name: notification_container
    ports:
      - "8085:8080"
    depends_on:
      - db

volumes:
  mysql_data:
