services:
  db:
    container_name: mysql-notification
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=db_notification'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secretroot'
      - 'MYSQL_USER=myuser'
    ports:
      - '3308:3306'
